### ISSUE TITLE
The vpn server app continues working if masquerading fails

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#464]
**Describe the bug**
If masquerading fails when starting the vpn-server app, the app does not work well, but it does not fail to start. This means that the vpn-server app appears as running in the manager UI, but the server in fact does not work.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start a visor as a normal user (not root).
2. Check the apps tab in the Skywire manager. The vpn-server app should appear as running.
3. Check the logs of the vpn-server app. It will show something like this (the last line shows the error):
```
level=info msg="Got app listener, bound to 44"
level=info msg="Got default network interface: enp0s3"
level=info msg="Old IP forwarding values:"
level=info msg="IPv4: 0, IPv6: 0"
level=info msg="Set IPv4 forwarding = 1"
level=info msg="Set IPv6 forwarding = 1"
level=info msg="Set IPv6 forwarding = 0"
level=info msg="Set IPv4 forwarding = 0"
level=error msg="Error serving" error="error enabling IP masquerading for enp0s3: error running command iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE: exit status 3"
```

**Actual behavior**
The app does not work correctly, but it appears as running.

**Expected behavior**
The app should completely fail to start.

**Comment by jdknives** [comment]
Fixed by #468 . Reopen if you find further issues. @Senyoret1

**Comment by Senyoret1** [comment]
@jdknives Not sure if I tested it correctly, but using the latest changes from the develop branch I still see the same error in the logs and the app appears as running in the manager
